import "./App.css";

import { useState } from "react";

function useLocalStorage(key, initialValue) {
  const [value, setStateValue] = useState(() => {
    const item = window.localStorage.getItem(key);
    return item ? JSON.parse(item) : initialValue;
  });

  const setValue = (value) => {
    setStateValue(value);
    window.localStorage.setItem(key, JSON.stringify(value));
  };

  return [value, setValue];
}

function fisherYates(array) {
  var count = array.length,
    randomnumber,
    temp;
  while (count) {
    randomnumber = (Math.random() * count--) | 0;
    temp = array[count];
    array[count] = array[randomnumber];
    array[randomnumber] = temp;
  }
}

export default function App() {
  const [lines, setLines] = useLocalStorage("lines", "");
  // 1 can never be generated by Math.random() -> [0, 1)
  const [output, setOutput] = useState(1);
  const [anon, setAnon] = useState(false);

  const links = lines.split("\n").filter((line) => line.trim());
  if (output !== 1) {
    fisherYates(links);
  }

  return (
    <div className="App">
      <div className="actions">
        <button onClick={() => setOutput(Math.random())}>Shuffle</button>
        <button onClick={() => setOutput(1)}>Reset</button>
      </div>
      <div>
        Anonymous: <input type="checkbox" checked={anon} onChange={e => setAnon(e.target.checked)} />
      </div>
      <ol>
        {links.map((link, i) => {
          const text = anon ? `link ${i + 1}` : link
          return (
            <li key={link}>
              <a href={link}>{text}</a>
            </li>
          );
        })}
      </ol>
      <textarea
        rows="10"
        style={{ width: "100%" }}
        onChange={(e) => setLines(e.target.value) && setOutput(1)}
        value={lines}
      ></textarea>
    </div>
  );
}
